/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NewGameImport } from './routes/new-game'
import { Route as IndexImport } from './routes/index'
import { Route as GameGameIdImport } from './routes/game/$gameId'

// Create/Update Routes

const NewGameRoute = NewGameImport.update({
  id: '/new-game',
  path: '/new-game',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GameGameIdRoute = GameGameIdImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/new-game': {
      id: '/new-game'
      path: '/new-game'
      fullPath: '/new-game'
      preLoaderRoute: typeof NewGameImport
      parentRoute: typeof rootRoute
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-game': typeof NewGameRoute
  '/game/$gameId': typeof GameGameIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-game': typeof NewGameRoute
  '/game/$gameId': typeof GameGameIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/new-game': typeof NewGameRoute
  '/game/$gameId': typeof GameGameIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new-game' | '/game/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new-game' | '/game/$gameId'
  id: '__root__' | '/' | '/new-game' | '/game/$gameId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewGameRoute: typeof NewGameRoute
  GameGameIdRoute: typeof GameGameIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewGameRoute: NewGameRoute,
  GameGameIdRoute: GameGameIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/new-game",
        "/game/$gameId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/new-game": {
      "filePath": "new-game.tsx"
    },
    "/game/$gameId": {
      "filePath": "game/$gameId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
